# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZGM4OGE0Yjc4MWIzYjFlZjYxZGJiNmNhY2Y5MDljZmExZDEzODZiOTJlNmNlNTFmNmIwZmM2MTg1MzkzZDZkODI4YzdmMWE3OGNkNGVkOGE2ZTlmZDJlMjFhMzk1MWQ5NzA5MjJkZmVjNjFiZmExZTc2MGEyN2Y4NmY3NDU0OTI=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
