# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MTdmMmJkYmU0MTJhNmM0OTE3NmE4Yzk5ZTM4M2M4YWQ5MWYyOWNhMzU2OTM5ZTllMWU4MjM5OTEwN2I3N2RkOWY5MzU3MjY0ZTVjM2ZiNjkzNjg3NzBhMDkzZGYwYThhNzViN2U2YTBhNmVmYTdhNDJhNDI4ZDZhMzYwZWQ0NGU=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
