apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: gcr.io/wise-coyote-827/blog
      context: ../blog
      jib: {}
    - image: gcr.io/wise-coyote-827/gateway
      context: ../gateway
      jib: {}
    - image: gcr.io/wise-coyote-827/store
      context: ../store
      jib: {}
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:latest'
deploy:
  kustomize: {}
