# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret:

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/

spring:
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: https://dev-6974382.okta.com/oauth2/default
        registration:
          oidc:
            client-id: 0oa3pkxski1zlp68L5d6
            client-secret: qv0kudNotbwjp6QHUnj1mmjI1FEIYXaBSVzC_Lgb
